version: '3.1'
services:
  backend:
    container_name: enoca_backend_project
    image: berkinyardimci/enoca-project
    build: ./
    ports:
      - "8000:8000"
    depends_on:
      - "PostgreSQL"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://PostgreSQL:5432/enoca_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1357
      SPRING_JPA_HIBERNATE_DDL_AUTO: create

  PostgreSQL:
    container_name: postgres_db
    image: postgres
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=1357
      - POSTGRES_USER=postgres
      - POSTGRES_DB=enoca_db