version: '3.1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/enoca_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1357
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    ports:
      - 5433:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 30s
      retries: 3
    environment:
      - POSTGRES_DB=enoca_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1357